### ISSUE TITLE
Showcase doesn't work in Firefox Win 68.0b6 (64-bit)

### ISSUE THREAD

**Issue by tomByrer** [sifrr/sifrr-elements#70]

**Comment by aadityataparia** [comment]
Sorry haven't got time to work on this. There are a lot of changes being done on sifrr-dom, so will update elements once I get time.

**Comment by aadityataparia** [comment]
Also can you please add a screenshot, AFAIK the carousel is not working.

**Comment by aadityataparia** [comment]
I have fixed most of it. Can you check now?

**Comment by tomByrer** [comment]
Still doesn't work, sorry  :/
![sifrr-elements-firefox](https://user-images.githubusercontent.com/1308419/67611920-b0b53780-f763-11e9-82ed-90363e8809d6.PNG)

**Comment by aadityataparia** [comment]
Will check on Firefox 😢

**Comment by aadityataparia** [comment]
Hi @tomByrer I found the bug and it is already fixed in sifrr-dom master. So it should be fixed in next release 😂
